version: '3'

services:
  frontend:
    build: ./front
    container_name: 'front'
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./front:/app
  backend:
    build: ./back
    container_name: 'back'
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    volumes:
      - /app/node_modules
      - ./back:/app
  mongo:
    image: mongo
    container_name: 'mongodb'
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: just_plan_it
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./back/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/db
  nginx:
    image: umputun/nginx-le:latest
    hostname: nginx
    restart: always
    container_name: nginx
    depends_on:
      - frontend
      - backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    logging:
      driver: json-file
      options:
          max-size: "10m"
          max-file: "5"

    volumes:
        - ./etc/ssl:/etc/nginx/ssl
        - ./etc/service-example.conf:/etc/nginx/service.conf
        # - ./etc/service-example-2.conf:/etc/nginx/service2.conf # more services, should be service*.conf
        # - ./etc/stream-example-2.conf:/etc/nginx/stream2.conf # more streams, should be stream*.conf
        - ./nginx:/etc/nginx/conf.d-le # configuration folder, all files from it will be added
        # - ./etc/stream.conf:/etc/nginx/stream.conf.d-le # streams configuration folder, all files from it will be added
    ports:
        - "80:80"
        - "443:443"

    environment:
        - TZ=Asia/Krasnoyarsk
        - LETSENCRYPT=true
        - LE_EMAIL=justplanitpro@justplanitpro.ru
        - LE_FQDN=justplanitpro.ru
  adminer:
    image: dockette/adminer:full
    container_name: adminer
    ports:
      - '8004:80'
volumes:
  mongo_data:
